USE covid_trends;

INSERT INTO health_regions SET hr_uid=1011, province_code=10, name_en="Eastern Regional Health Authority", name_fr="Eastern Regional Health Authority";
INSERT INTO health_regions SET hr_uid=1012, province_code=10, name_en="Central Regional Health Authority", name_fr="Central Regional Health Authority";
INSERT INTO health_regions SET hr_uid=1013, province_code=10, name_en="Western Regional Health Authority", name_fr="Western Regional Health Authority";
INSERT INTO health_regions SET hr_uid=1014, province_code=10, name_en="Labrador-Grenfell Regional Health Authority", name_fr="Labrador-Grenfell Regional Health Authority";
INSERT INTO health_regions SET hr_uid=1100, province_code=11, name_en="Prince Edward Island", name_fr="Île-du-Prince-Édouard";
INSERT INTO health_regions SET hr_uid=1201, province_code=12, name_en="Zone 1 - Western	", name_fr="Zone 1 - Western";
INSERT INTO health_regions SET hr_uid=1202, province_code=12, name_en="Zone 2 - Northern", name_fr="Zone 2 - Northern";
INSERT INTO health_regions SET hr_uid=1203, province_code=12, name_en="Zone 3 - Eastern", name_fr="Zone 3 - Eastern";
INSERT INTO health_regions SET hr_uid=1204, province_code=12, name_en="Zone 4 - Central", name_fr="Zone 4 - Central";
INSERT INTO health_regions SET hr_uid=1301, province_code=13, name_en="Zone 1 (Moncton area)", name_fr="Zone 1 (région de Moncton)";
INSERT INTO health_regions SET hr_uid=1302, province_code=13, name_en="Zone 2 (Saint John area)", name_fr="Zone 2 (région de Saint John)";
INSERT INTO health_regions SET hr_uid=1303, province_code=13, name_en="Zone 3 (Fredericton area)", name_fr="Zone 3 (région de Fredericton)";
INSERT INTO health_regions SET hr_uid=1304, province_code=13, name_en="Zone 4 (Edmundston area)", name_fr="Zone 4 (région d'Edmundston)";
INSERT INTO health_regions SET hr_uid=1305, province_code=13, name_en="Zone 5 (Campbellton area)", name_fr="Zone 5 (région de Campbellton)";
INSERT INTO health_regions SET hr_uid=1306, province_code=13, name_en="Zone 6 (Bathurst area)", name_fr="Zone 6 (région de Bathurst)";
INSERT INTO health_regions SET hr_uid=1307, province_code=13, name_en="Zone 7 (Miramichi area)", name_fr="Zone 7 (région de Miramichi)";
INSERT INTO health_regions SET hr_uid=2401, province_code=24, name_en="Région du Bas-Saint-Laurent", name_fr="Région du Bas-Saint-Laurent";
INSERT INTO health_regions SET hr_uid=2402, province_code=24, name_en="Région du Saguenay—Lac-Saint-Jean", name_fr="Région du Saguenay—Lac-Saint-Jean";
INSERT INTO health_regions SET hr_uid=2403, province_code=24, name_en="Région de la Capitale-Nationale", name_fr="Région de la Capitale-Nationale";
INSERT INTO health_regions SET hr_uid=2404, province_code=24, name_en="Région de la Mauricie et du Centre-du-Québec", name_fr="Région de la Mauricie et du Centre-du-Québec";
INSERT INTO health_regions SET hr_uid=2405, province_code=24, name_en="Région de l'Estrie", name_fr="Région de l'Estrie";
INSERT INTO health_regions SET hr_uid=2406, province_code=24, name_en="Région de Montréal", name_fr="Région de Montréal";
INSERT INTO health_regions SET hr_uid=2407, province_code=24, name_en="Région de l'Outaouais", name_fr="Région de l'Outaouais";
INSERT INTO health_regions SET hr_uid=2408, province_code=24, name_en="Région de l'Abitibi-Témiscamingue", name_fr="Région de l'Abitibi-Témiscamingue";
INSERT INTO health_regions SET hr_uid=2409, province_code=24, name_en="Région de la Côte-Nord", name_fr="Région de la Côte-Nord";
INSERT INTO health_regions SET hr_uid=2410, province_code=24, name_en="Région du Nord-du-Québec", name_fr="Région du Nord-du-Québec";
INSERT INTO health_regions SET hr_uid=2411, province_code=24, name_en="Région de la Gaspésie—Îles-de-la-Madeleine", name_fr="Région de la Gaspésie—Îles-de-la-Madeleine";
INSERT INTO health_regions SET hr_uid=2412, province_code=24, name_en="Région de la Chaudière-Appalaches", name_fr="Région de la Chaudière-Appalaches";
INSERT INTO health_regions SET hr_uid=2413, province_code=24, name_en="Région de Laval", name_fr="Région de Laval";
INSERT INTO health_regions SET hr_uid=2414, province_code=24, name_en="Région de Lanaudière", name_fr="Région de Lanaudière";
INSERT INTO health_regions SET hr_uid=2415, province_code=24, name_en="Région des Laurentides", name_fr="Région des Laurentides";
INSERT INTO health_regions SET hr_uid=2416, province_code=24, name_en="Région de la Montérégie", name_fr="Région de la Montérégie";
INSERT INTO health_regions SET hr_uid=2417, province_code=24, name_en="Région du Nunavik", name_fr="Région du Nunavik";
INSERT INTO health_regions SET hr_uid=2418, province_code=24, name_en="Région des Terres-Cries-de-la-Baie-James", name_fr="Région des Terres-Cries-de-la-Baie-James";
INSERT INTO health_regions SET hr_uid=3526, province_code=35, name_en="The District of Algoma Health Unit", name_fr="Circonscription sanitaire du district d'Algoma";
INSERT INTO health_regions SET hr_uid=3527, province_code=35, name_en="Brant County Health Unit", name_fr="Circonscription sanitaire du comté de Brant";
INSERT INTO health_regions SET hr_uid=3530, province_code=35, name_en="Durham Regional Health Unit", name_fr="Circonscription sanitaire régionale de Durham";
INSERT INTO health_regions SET hr_uid=3533, province_code=35, name_en="Grey Bruce Health Unit", name_fr="Circonscription sanitaire de Grey Bruce";
INSERT INTO health_regions SET hr_uid=3534, province_code=35, name_en="Haldimand-Norfolk Health Unit", name_fr="Circonscription sanitaire de Haldimand-Norfolk";
INSERT INTO health_regions SET hr_uid=3535, province_code=35, name_en="Haliburton, Kawartha, Pine Ridge District Health Unit", name_fr="Circonscription sanitaire du district de Haliburton, Kawartha et Pine Ridge";
INSERT INTO health_regions SET hr_uid=3536, province_code=35, name_en="Halton Regional Health Unit", name_fr="Circonscription sanitaire régionale de Halton";
INSERT INTO health_regions SET hr_uid=3537, province_code=35, name_en="City of Hamilton Health Unit", name_fr="Circonscription sanitaire de la cité de Hamilton";
INSERT INTO health_regions SET hr_uid=3538, province_code=35, name_en="Hastings and Prince Edward Counties Health Unit", name_fr="Circonscription sanitaire des comtés de Hastings et Prince Edward";
INSERT INTO health_regions SET hr_uid=3539, province_code=35, name_en="Huron County Health Unit", name_fr="Circonscription sanitaire du comté de Huron";
INSERT INTO health_regions SET hr_uid=3540, province_code=35, name_en="Chatham-Kent Health Unit", name_fr="Circonscription sanitaire de Chatham-Kent";
INSERT INTO health_regions SET hr_uid=3541, province_code=35, name_en="Kingston, Frontenac and Lennox and Addington Health Unit", name_fr="Circonscription sanitaire de Kingston, Frontenac et Lennox et Addington";
INSERT INTO health_regions SET hr_uid=3542, province_code=35, name_en="Lambton Health Unit", name_fr="Circonscription sanitaire de Lambton";
INSERT INTO health_regions SET hr_uid=3543, province_code=35, name_en="Leeds, Grenville and Lanark District Health Unit", name_fr="Circonscription sanitaire du district de Leeds, Grenville et Lanark";
INSERT INTO health_regions SET hr_uid=3544, province_code=35, name_en="Middlesex-London Health Unit", name_fr="Circonscription sanitaire de Middlesex-London";
INSERT INTO health_regions SET hr_uid=3546, province_code=35, name_en="Niagara Regional Area Health Unit", name_fr="Circonscription sanitaire régionale de Niagara";
INSERT INTO health_regions SET hr_uid=3547, province_code=35, name_en="North Bay Parry Sound District Health Unit", name_fr="Circonscription sanitaire du district de North Bay Parry Sound";
INSERT INTO health_regions SET hr_uid=3549, province_code=35, name_en="Northwestern Health Unit", name_fr="Circonscription sanitaire du Nord-Ouest";
INSERT INTO health_regions SET hr_uid=3551, province_code=35, name_en="City of Ottawa Health Unit", name_fr="Circonscription sanitaire de la ville d'Ottawa";
INSERT INTO health_regions SET hr_uid=3553, province_code=35, name_en="Peel Regional Health Unit", name_fr="Circonscription sanitaire régionale de Peel";
INSERT INTO health_regions SET hr_uid=3554, province_code=35, name_en="Perth District Health Unit", name_fr="Circonscription sanitaire du district de Perth";
INSERT INTO health_regions SET hr_uid=3555, province_code=35, name_en="Peterborough County–City Health Unit", name_fr="Circonscription sanitaire du comté et de la cité de Peterborough";
INSERT INTO health_regions SET hr_uid=3556, province_code=35, name_en="Porcupine Health Unit", name_fr="Circonscription sanitaire de Porcupine";
INSERT INTO health_regions SET hr_uid=3557, province_code=35, name_en="Renfrew County and District Health Unit", name_fr="Circonscription sanitaire du comté et du district de Renfrew";
INSERT INTO health_regions SET hr_uid=3558, province_code=35, name_en="The Eastern Ontario Health Unit", name_fr="Circonscription sanitaire de l'Est de l'Ontario";
INSERT INTO health_regions SET hr_uid=3560, province_code=35, name_en="Simcoe Muskoka District Health Unit", name_fr="Circonscription sanitaire du district de Simcoe Muskoka";
INSERT INTO health_regions SET hr_uid=3561, province_code=35, name_en="Sudbury and District Health Unit", name_fr="Circonscription sanitaire de Sudbury et son district";
INSERT INTO health_regions SET hr_uid=3562, province_code=35, name_en="Thunder Bay District Health Unit", name_fr="Circonscription sanitaire du district de Thunder Bay";
INSERT INTO health_regions SET hr_uid=3563, province_code=35, name_en="Timiskaming Health Unit", name_fr="Circonscription sanitaire de Timiskaming";
INSERT INTO health_regions SET hr_uid=3565, province_code=35, name_en="Waterloo Health Unit", name_fr="Circonscription sanitaire de Waterloo";
INSERT INTO health_regions SET hr_uid=3566, province_code=35, name_en="Wellington-Dufferin-Guelph Health Unit", name_fr="Circonscription sanitaire de Wellington-Dufferin-Guelph";
INSERT INTO health_regions SET hr_uid=3568, province_code=35, name_en="Windsor-Essex County Health Unit", name_fr="Circonscription sanitaire de Windsor-comté d'Essex";
INSERT INTO health_regions SET hr_uid=3570, province_code=35, name_en="York Regional Health Unit", name_fr="Circonscription sanitaire régionale de York";
INSERT INTO health_regions SET hr_uid=3575, province_code=35, name_en="Oxford Elgin St. Thomas Health Unit", name_fr="Circonscription sanitaire d’Oxford, Elgin et St. Thomas";
INSERT INTO health_regions SET hr_uid=3595, province_code=35, name_en="City of Toronto Health Unit", name_fr="Circonscription sanitaire de la cité de Toronto";
INSERT INTO health_regions SET hr_uid=4601, province_code=46, name_en="Winnipeg Regional Health Authority", name_fr="Office régional de la santé de Winnipeg";
INSERT INTO health_regions SET hr_uid=4602, province_code=46, name_en="Prairie Mountain Health", name_fr="Santé de Prairie Mountain";
INSERT INTO health_regions SET hr_uid=4603, province_code=46, name_en="Interlake-Eastern Regional Health Authority", name_fr="Office régional de la santé d'Entre-les-Lacs et de l'Est";
INSERT INTO health_regions SET hr_uid=4604, province_code=46, name_en="Northern Regional Health Authority", name_fr="Office régional de la santé du Nord";
INSERT INTO health_regions SET hr_uid=4605, province_code=46, name_en="Southern Health—Santé Sud", name_fr="Southern Health—Santé Sud";
INSERT INTO health_regions SET hr_uid=471, province_code=47, name_en="Far North", name_fr="Far North";
INSERT INTO health_regions SET hr_uid=472, province_code=47, name_en="North", name_fr="North";
INSERT INTO health_regions SET hr_uid=473, province_code=47, name_en="Central", name_fr="Central";
INSERT INTO health_regions SET hr_uid=474, province_code=47, name_en="Saskatoon", name_fr="Saskatoon";
INSERT INTO health_regions SET hr_uid=475, province_code=47, name_en="Regina", name_fr="Regina";
INSERT INTO health_regions SET hr_uid=476, province_code=47, name_en="South", name_fr="South";
INSERT INTO health_regions SET hr_uid=4831, province_code=48, name_en="South Zone", name_fr="South Zone";
INSERT INTO health_regions SET hr_uid=4832, province_code=48, name_en="Calgary Zone", name_fr="Calgary Zone";
INSERT INTO health_regions SET hr_uid=4833, province_code=48, name_en="Central Zone", name_fr="Central Zone";
INSERT INTO health_regions SET hr_uid=4834, province_code=48, name_en="Edmonton Zone", name_fr="Edmonton Zone";
INSERT INTO health_regions SET hr_uid=4835, province_code=48, name_en="North Zone", name_fr="North Zone";
INSERT INTO health_regions SET hr_uid=591, province_code=59, name_en="Fraser Health", name_fr="Fraser Health";
INSERT INTO health_regions SET hr_uid=592, province_code=59, name_en="Interior Health", name_fr="Interior Health";
INSERT INTO health_regions SET hr_uid=593, province_code=59, name_en="Vancouver Island Health", name_fr="Vancouver Island Health";
INSERT INTO health_regions SET hr_uid=594, province_code=59, name_en="Northern Health", name_fr="Northern Health";
INSERT INTO health_regions SET hr_uid=595, province_code=59, name_en="Vancouver Coastal Health", name_fr="Vancouver Coastal Health";
INSERT INTO health_regions SET hr_uid=6001, province_code=60, name_en="Yukon", name_fr="Yukon";
INSERT INTO health_regions SET hr_uid=6101, province_code=61, name_en="Northwest Territories", name_fr="Territoires du Nord-Ouest";
INSERT INTO health_regions SET hr_uid=6201, province_code=62, name_en="Nunavut", name_fr="Nunavut";